(function(){
const W="260978955714";
const css=`#laBtn{position:fixed;right:18px;bottom:18px;width:58px;height:58px;border:0;border-radius:50%;background:#17131a;color:#fff;font-size:25px;box-shadow:0 8px 25px #0003;z-index:99999}#laBox{position:fixed;right:18px;bottom:88px;width:min(360px,calc(100vw - 28px));height:500px;background:#fff;border-radius:20px;box-shadow:0 15px 45px #0003;overflow:hidden;z-index:99999;display:none;font-family:Arial,sans-serif;border:1px solid #eadce4}#laBox.open{display:flex;flex-direction:column}.laHead{background:#17131a;color:#fff;padding:15px}.laClose{float:right;background:none;border:0;color:#fff;font-size:22px}.laMsgs{flex:1;padding:14px;overflow:auto;background:#fff8fc}.laMsg{max-width:85%;padding:10px 12px;border-radius:15px;margin:7px 0;font-size:14px;line-height:1.4}.bot{background:#fff;border:1px solid #eee0e7}.usr{background:#ead0dd;margin-left:auto}.laBtns{padding:10px;display:flex;flex-wrap:wrap;gap:7px;border-top:1px solid #eee}.laBtns button{border:1px solid #cfa7bb;background:#fff;padding:8px;border-radius:18px}.laInput{display:flex;border-top:1px solid #eee}.laInput input{flex:1;border:0;padding:13px;outline:0}.laInput button{background:#17131a;color:#fff;border:0;padding:0 15px}@media(max-width:480px){#laBox{right:10px;bottom:82px;width:calc(100vw - 20px);height:68vh}}`;
const st=document.createElement("style");st.textContent=css;document.head.appendChild(st);
const b=document.createElement("button");b.id="laBtn";b.innerHTML="💬";document.body.appendChild(b);
const box=document.createElement("div");box.id="laBox";box.innerHTML=`<div class="laHead"><b>Lele's Cosmetics</b><button class="laClose">×</button><div style="font-size:11px;color:#e5b5ca">Customer assistant</div></div><div class="laMsgs" id="laMsgs"></div><div class="laBtns"><button data-q="Perfumes">Perfumes</button><button data-q="Prices">Prices</button><button data-q="Body oils">Body oils</button><button data-q="How do I order?">How to order</button><button data-q="Delivery">Delivery</button></div><div class="laInput"><input id="laIn" placeholder="Ask Lele's Cosmetics..."><button id="laSend">Send</button></div>`;document.body.appendChild(box);
const msgs=box.querySelector("#laMsgs"),input=box.querySelector("#laIn");
function add(t,u=false){let d=document.createElement("div");d.className="laMsg "+(u?"usr":"bot");d.innerHTML=t;msgs.appendChild(d);msgs.scrollTop=msgs.scrollHeight}
function reply(q){q=q.toLowerCase();if(/perfume|fragrance|scent/.test(q))return"🌸 We have perfumes including Malikat Al Arab, Ameerat Al Arab, Kiara Pistachio Frost, Farfashah and other fragrances. Perfumes are <b>K100–K200</b>.";if(/oil/.test(q))return"✨ Body oils are <b>K75</b>.";if(/price|cost|how much/.test(q))return"🌸 Perfumes: <b>K100–K200</b><br>✨ Body oils: <b>K75</b>";if(/order|buy|purchase/.test(q))return"Choose your product and message us on WhatsApp with your order and delivery details.<br><br><a href='https://wa.me/"+W+"' target='_blank'><b>📲 Order on WhatsApp</b></a>";if(/deliver|delivery|location/.test(q))return"Yes, <b>we deliver</b>. Send us your location and the product you want on WhatsApp.";if(/contact|whatsapp|phone|number|call/.test(q))return"WhatsApp: <b>0978955714</b><br><a href='https://wa.me/"+W+"' target='_blank'><b>Open WhatsApp</b></a>";if(/hello|hi|hey/.test(q))return"Hello! 👋 Welcome to Lele's Cosmetics. I can help with perfumes, body oils, prices, ordering and delivery.";return"I can help with <b>perfumes, body oils, prices, ordering and delivery</b>. Try asking “How much are the perfumes?”"};
function send(v){v=(v||input.value).trim();if(!v)return;add(v,true);input.value="";setTimeout(()=>add(reply(v)),150)}
b.onclick=()=>{box.classList.toggle("open");if(box.classList.contains("open")&&!msgs.children.length)add("Hello! 👋 Welcome to <b>Lele's Cosmetics</b>.<br><br>I can help with perfumes, body oils, prices, ordering and delivery.");if(box.classList.contains("open"))input.focus()};box.querySelector(".laClose").onclick=()=>box.classList.remove("open");box.querySelector("#laSend").onclick=()=>send();input.onkeydown=e=>{if(e.key==="Enter")send()};box.querySelector(".laBtns").onclick=e=>{if(e.target.dataset.q)send(e.target.dataset.q)}
})();
<script src="agent.js"></script>
